module.exports = ({ PROJECT_NAME, PROJECT_TITLE, USE_REDUX, USE_ANTD, USE_AXIOS, USE_LESS, USE_SCSS }) => {
  return [
    `{`,
    `  "name": "${PROJECT_NAME}",`,
    `  "version": "1.0.0",`,
    `  "description": "${PROJECT_TITLE}",`,
    `  "scripts": {`,
    `    "dev": "ts-rc dev",`,
    `    "build": "ts-rc build"`,
    `  },`,
    `  "author": "",`,
    `  "license": "ISC",`,
    `  "dependencies": {`,
    USE_ANTD && `    "antd": "^4.10.2",`,
    USE_AXIOS && `    "axios": "^0.21.1",`,
    USE_REDUX && `    "redux": "^4.0.5",`,
    USE_REDUX && `    "redux-thunk": "^2.3.0",`,
    USE_REDUX && `    "react-redux": "^7.2.2",`,
    `    "react": "^17.0.1",`,
    `    "react-dom": "^17.0.1",`,
    `    "react-router-dom": "^5.2.0"`,
    `  }`,
    `  "devDependencies": {`,
    `    "@types/react-dom": "^17.0.0",`,
    `    "@types/react-router-dom": "^5.1.7",`,
    USE_REDUX && `    "@types/react-redux": "^7.1.15",`,
    USE_LESS && `    "less": "^4.1.0",`,
    USE_LESS && `    "less-loader": "^7.2.1",`,
    USE_SCSS && `    "node-sass": "^5.0.0",`,
    USE_SCSS && `    "sass-loader": "^10.1.1"`,
    `    "ts-rc-cli": "^0.0.1-alpha.3"`,
    `  },`,
    `}`,
    ``,
  ]
}
