module.exports = ({
  CLI_PACKAGE_VERSION,
  PROJECT_NAME,
  PROJECT_TITLE,
  USE_REDUX,
  USE_ANTD,
  USE_AXIOS,
  USE_LESS,
  USE_SCSS,
}) => {
  return [
    `{`,
    `  "name": "${PROJECT_NAME}",`,
    `  "version": "1.0.0",`,
    `  "description": "${PROJECT_TITLE}",`,
    `  "scripts": {`,
    `    "dev": "ts-rc dev",`,
    `    "build": "ts-rc build",`,
    `    "lint": "eslint --ext .ts,.tsx src"`,
    `  },`,
    `  "author": "",`,
    `  "license": "ISC",`,
    `  "dependencies": {`,
    USE_ANTD && `    "antd": "^4.15.0",`,
    USE_AXIOS && `    "axios": "^0.21.1",`,
    USE_REDUX && `    "redux": "^4.0.5",`,
    USE_REDUX && `    "redux-thunk": "^2.3.0",`,
    USE_REDUX && `    "react-redux": "^7.2.3",`,
    `    "react": "^17.0.2",`,
    `    "react-dom": "^17.0.2",`,
    `    "react-router-dom": "^5.2.0"`,
    `  },`,
    `  "devDependencies": {`,
    `    "@types/react-dom": "^17.0.3",`,
    `    "@types/react-router-dom": "^5.1.7",`,
    USE_REDUX && `    "@types/react-redux": "^7.1.16",`,
    USE_LESS && `    "less": "^4.1.1",`,
    USE_LESS && `    "less-loader": "^8.0.0",`,
    USE_SCSS && `    "node-sass": "^5.0.0",`,
    USE_SCSS && `    "sass-loader": "^10.1.1",`,
    `    "ts-rc-cli": "^${CLI_PACKAGE_VERSION}",`,
    `    "typescript": "^4.2.4",`,
    `    "webpack": "^5.31.0"`,
    `  }`,
    `}`,
    ``,
  ]
}
