module.exports = ({ USE_ANTD, USE_AXIOS, PROJECT_TITLE, PROJECT_NAME }) => {
  const btnStr = USE_ANTD ? 'Button' : 'button'

  return [
    `import React from 'react'`,
    USE_ANTD && `import { Button, Card } from 'antd'`,
    ``,
    `interface DemoProps extends PageProps {`,
    `  id?: number`,
    `}`,
    ``,
    `declare interface DemoState {`,
    `  count: number`,
    `}`,
    ``,
    `export default class Demo extends React.Component<DemoProps, DemoState> {`,
    `  state: DemoState = {`,
    `    count: 1,`,
    `  }`,
    ``,
    `  componentDidMount() {`,
    `    console.log(this)`,
    `  }`,
    ``,
    `  render() {`,
    `    const { count } = this.state`,
    `    return (`,
    `      <Card title="${PROJECT_NAME || PROJECT_TITLE}" className="full-screen-min">`,
    `        <p>state count : {count}</p>`,
    `        <div className="mt-16">`,
    `          <${btnStr}`,
    USE_ANTD && `            type="primary"`,
    `            onClick={() => {`,
    `              this.setState({ count: count + 1 })`,
    `            }}`,
    `          >`,
    `            add`,
    `          </${btnStr}>`,
    ...(USE_AXIOS
      ? [
          ``,
          `          <${btnStr}`,
          `            className="ml-16"`,
          `            onClick={() => {`,
          `              this.queryData()`,
          `            }}`,
          `          >`,
          `            request`,
          `          </${btnStr}>`,
        ]
      : []),
    `        </div>`,
    `      </Card>`,
    `    )`,
    `  }`,
    ...(USE_AXIOS
      ? [
          ``,
          `  queryData() {`,
          `    $api.test.queryTestInfo({}).then((res) => {`,
          `      console.log(res)`,
          `    })`,
          `  }`,
        ]
      : []),
    `} // class Demo end`,
    ``,
  ]
}
