module.exports = ({ USE_ANTD }) => {
  const btnStr = USE_ANTD ? 'Button' : 'button'

  return [
    `import React from 'react'`,
    USE_ANTD && `import { Button } from 'antd'`,
    ``,
    `interface DemoProps extends PageProps, StoreProps {`,
    `  id?: number`,
    `}`,
    ``,
    `declare interface DemoState {`,
    `  count: number`,
    `}`,
    ``,
    `export default class Demo extends React.Component<DemoProps, DemoState> {`,
    `  state: DemoState = {`,
    `    count: 1,`,
    `  }`,
    ``,
    `  componentDidMount() {`,
    `    console.log(this)`,
    `  }`,
    ``,
    `  render() {`,
    `    const { count } = this.state`,
    `    return (`,
    `      <div>`,
    `        <div className="panel">`,
    `          <p>state count : {count}</p>`,
    `          <div className="mt-16">`,
    `            <${btnStr}`,
    USE_ANTD && `              type="primary"`,
    `              onClick={() => {`,
    `                this.setState({ count: count + 1 })`,
    `              }}`,
    `            >`,
    `              add`,
    `            </${btnStr}>`,
    ``,
    `            <${btnStr}`,
    `              className="ml-16"`,
    `              onClick={() => {`,
    `                this.queryData()`,
    `              }}`,
    `            >`,
    `              request`,
    `            </${btnStr}>`,
    `          </div>`,
    `        </div>`,
    `      </div>`,
    `    )`,
    `  }`,
    ``,
    `  queryData() {`,
    `    $api.test.queryTestInfo({}).then((res) => {`,
    `      console.log(res)`,
    `    })`,
    `  }`,
    `} // class Demo end`,
    ``,
  ]
}
